Add release-hook to check for missing GIT tag
Signed-off-by: Joachim Nilsson <troglobit@gmail.com>

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -4,17 +4,37 @@ dist_man1_MANS = mg.1
 doc_DATA       = README.md ChangeLog.md UNLICENSE tutorial .mg
 EXTRA_DIST     = README.md ChangeLog.md UNLICENSE tutorial .mg
 
-# lintian --profile debian -i -I --show-overrides ../$PKG.changes
-package:
-	dpkg-buildpackage -uc -us -B
-
-#
-# Target to run when building a release
-#
-release: distcheck package
+## Generate MD5 checksum file
+MD5 = md5sum
+md5-dist:
 	@for file in $(DIST_ARCHIVES); do	\
-		md5sum $$file > ../$$file.md5;	\
+		$(MD5) $$file > ../$$file.md5;	\
 	done
+
+## Check if tagged in git
+release-hook:
+	@if [ ! `git tag | grep $(PACKAGE_VERSION)` ]; then				\
+		echo;									\
+		printf "\e[1m\e[41mCannot find release tag $(PACKAGE_VERSION)\e[0m\n";	\
+		printf "\e[1m\e[5mDo release anyway?\e[0m "; read yorn;			\
+		if [ "$$yorn" != "y" -a "$$yorn" != "Y" ]; then				\
+			printf "OK, aborting release.\n";				\
+			exit 1;								\
+		fi;									\
+		echo;									\
+	else										\
+		echo;									\
+		printf "\e[1m\e[42mFound GIT release tag $(PACKAGE_VERSION)\e[0m\n";	\
+		printf "\e[1m\e[44m>>Remember to push tags!\e[0m\n";			\
+		echo;									\
+	fi
+
+# lintian --profile debian -i -I --show-overrides ../$PKG.changes
+package build-deb:
+	@dpkg-buildpackage -uc -us -B
+
+## Target to run when building a release
+release: release-hook distcheck package md5-dist
 	@mv $(DIST_ARCHIVES) ../
 	@echo
 	@echo "Resulting release files:"
